# Generated by Django 3.1.2 on 2020-10-27 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20201027_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
