version: '3'

services:
    apache:
        container_name: django
        build: .
        restart: always
        volumes:
            - ./www:/var/site
            - ../articles:/var/articles
            - ./apache:/etc/apache2
            - /var/log/culture-numerique/apache2:/var/log/apache2
        environment:
            #Databases settings
            - DB_PASS
            - DB_USER
            - DB_NAME
            - DB_HOST
            - DB_PORT

            - PRODUCTION
            - DOMAIN
            - SERVER_PORT
            - SECRET_KEY

            #Mail settings
            - ADMIN_MAIL
            - EMAIL_USER
            - EMAIL_PASS
            - EMAIL_HOST
            - EMAIL_PORT
            
            #Encoding
            - PYTHONIOENCODING=UTF-8
        networks:
            - django-net
        ports:
            - "80:$SERVER_PORT"
            - "443:443"

    mysql:
        container_name: mysql
        image: mariadb:10.3
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASS}
        networks:
            - django-net

networks:
    django-net:
        driver: bridge
