version: '3'

services:
    apache:
        container_name: django
        build: .
        volumes:
            - ./www:/var/site
            - ../articles:/var/articles
        environment:
            #Databases settings
            - DB_PASS
            - DB_USER
            - DB_NAME
            - DB_PORT
            
            #Encoding
            - PYTHONIOENCODING=UTF-8
        networks:
            - django-net
        ports:
            - "80:8000"
            - "443:443"

    mysql:
        container_name: mysql
        image: mariadb:10.3
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASS}
        networks:
            - django-net

networks:
    django-net:
        driver: bridge
